name: 'Check Loser Homework'
description: 'Use cmake to check loser homework'
inputs:
  shell:
    description: 'shell to use'
    required: false
    default: bash
  build-path:
    description: 'path to build'
    required: false
    default: 'build'
  extra-gen-params:
    description: 'extra cmake generation parameters'
    required: false
    default: ''
runs:
  using: "composite"
  steps: 
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    - run: pip install -r requirements.txt
      shell: ${{ inputs.shell }}

    - name: Configure CMake
      run: cmake -B ${{ inputs.build-path }} ${{ inputs.extra-gen-params}}
      shell: ${{ inputs.shell }}

    - name: Build
      run: cmake --build ${{ inputs.build-path }} --target build_loser_homework
      shell: ${{ inputs.shell }}

    - name: Check run
      run: cmake --build ${{ inputs.build-path }} --target run_loser_homework
      shell: ${{ inputs.shell }}