name: Build TeX files

on:
  workflow_dispatch: 

jobs:
  build-to-lfs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install ghostscript
      run: |
        sudo apt update
        sudo apt install ghostscript
    
    - name: Install TeX Live
      uses: zauguin/install-texlive@v3
      with:
        package_file: .github/tl_packages
      
    - name: Install latexmk
      run: |
        tlmgr install latexmk
    
    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build -DBUILD_DOCS=ON -DBUILD_PROG=OFF
    
    - name: Build
      run: cmake --build ${{github.workspace}}/build

    # - name: Copy build files
    #   run: cp -r build/docs .
    
    # - name: Git commit
    #   run: |
    #     git config user.name github-actions
    #     git config user.email github-actions@github.com
    #     git add .
    #     git commit -m "chore: update generated docs"
    #     git push

    - name: Update artifacts
      uses: actions/upload-artifact@v4
      with:
        name: docs
        path: build/docs