name: Build TeX files

on:
  workflow_dispatch: 

jobs:
  build-to-lfs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install ghostscript and latexmk
      run: |
        sudo apt update
        sudo apt install ghostscript latexmk
    
    - name: Install TeX Live
      uses: zauguin/install-texlive@v3
      with:
        package_file: .github/tl_packages
    
    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build -DBUILD_DOCS=ON -DBUILD_PROG=OFF
    
    - name: Build
      run: cmake --build ${{github.workspace}}/build