name: Check all loser homework

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/**'
      - '**.cmake'
      - 'CMakeLists.txt'
      - 'src/群友提交/**'
      - '!src/群友提交/**.cpp'
      - '!src/群友提交/**.cxx'
      - '!src/群友提交/**.cc'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/**'
      - '**.cmake'
      - 'CMakeLists.txt'
      - 'src/群友提交/**'
      - '!src/群友提交/**.cpp'
      - '!src/群友提交/**.cxx'
      - '!src/群友提交/**.cc'

jobs:
  check-in-gcc:
    runs-on: ubuntu-latest
    env:
      cxx_compiler: g++-13

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install -r requirements.txt

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_CXX_COMPILER=$cxx_compiler

      - name: Build
        run: cmake --build ${{github.workspace}}/build --target build_loser_homework

      - name: Check run
        run: cmake --build ${{github.workspace}}/build --target run_loser_homework

  check-in-clang:
    runs-on: ubuntu-latest
    env:
      cxx_compiler: clang++-17

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install -r requirements.txt

      - name: Install clang 17
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod u+x llvm.sh
          echo | sudo ./llvm.sh 17

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_CXX_COMPILER=$cxx_compiler

      - name: Build
        run: cmake --build ${{github.workspace}}/build --target build_loser_homework

      - name: Check run
        run: cmake --build ${{github.workspace}}/build --target run_loser_homework

  check-in-msvc:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install -r requirements.txt

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build

      - name: Build
        run: cmake --build ${{github.workspace}}/build --target build_loser_homework

      - name: Check run
        run: cmake --build ${{github.workspace}}/build --target run_loser_homework
