name: Check all loser homework

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/**'
      - '**.cmake'
      - 'CMakeLists.txt'
      - 'src/群友提交/**'
      - '!src/群友提交/**.cpp'
      - '!src/群友提交/**.cxx'
      - '!src/群友提交/**.cc'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/**'
      - '**.cmake'
      - 'CMakeLists.txt'
      - 'src/群友提交/**'
      - '!src/群友提交/**.cpp'
      - '!src/群友提交/**.cxx'
      - '!src/群友提交/**.cc'

jobs:
  check-in-gcc:
    runs-on: ubuntu-latest
    env:
      cxx_compiler: g++-13

    steps:
      - uses: actions/checkout@v4

      - name: Check loser homework 
        uses: ./.github/actions/check-loser-homework
        with:
          build-path: ${{github.workspace}}/build
          extra-gen-params: "-DCMAKE_CXX_COMPILER=$cxx_compiler"

  check-in-clang:
    runs-on: ubuntu-latest
    env:
      cxx_compiler: clang++-17

    steps:
      - uses: actions/checkout@v4

      - name: Install clang 17
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod u+x llvm.sh
          echo | sudo ./llvm.sh 17

      - name: Check loser homework 
        uses: ./.github/actions/check-loser-homework
        with:
          build-path: ${{github.workspace}}/build
          extra-gen-params: "-DCMAKE_CXX_COMPILER=$cxx_compiler"

  check-in-msvc:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - name: Check loser homework 
        uses: ./.github/actions/check-loser-homework
        with:
          build-path: ${{github.workspace}}/build
          shell: pwsh
