name: Check changed loser homework

env:
  src_path: "src/群友提交"

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/群友提交/**.cpp'
      - 'src/群友提交/**.cxx'
      - 'src/群友提交/**.cc'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/群友提交/**.cpp'
      - 'src/群友提交/**.cxx'
      - 'src/群友提交/**.cc'

jobs:
  get-changed-files:
    runs-on: ubuntu-latest
    outputs:
      changed_cpp_files: ${{ steps.changed-cpp-files.outputs.all_changed_files }}
      any_changed: ${{ steps.changed-cpp-files.outputs.any_changed }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed cpp files
        id: changed-cpp-files
        uses: tj-actions/changed-files@v42
        with:
          separator: ";"
          quotepath: "false"
          files: |
            **.cpp
            **.cc
            **.cxx

      - name: List all changed cpp files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-cpp-files.outputs.all_changed_files }}
        run: |
          IFS=';' read -ra FILES <<< "$ALL_CHANGED_FILES"
          for file in "${FILES[@]}"; do
            echo "$file was changed"
          done

  check-in-gcc:
    needs: get-changed-files
    runs-on: ubuntu-latest
    env:
      cxx_compiler: g++-13

    steps:
      - uses: actions/checkout@v4

      - name: Only keep cpp changed files
        if: needs.get-changed-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ needs.get-changed-files.outputs.changed_cpp_files }}
        shell: pwsh
        run: ./.github/workflows/Remove-UnchangedFile.ps1

      - name: Check loser homework 
        if: needs.get-changed-files.outputs.any_changed == 'true'
        uses: ./.github/actions/check-loser-homework
        with:
          build-path: ${{github.workspace}}/build
          extra-gen-params: "-DCMAKE_CXX_COMPILER=$cxx_compiler"

  check-in-clang:
    needs: get-changed-files
    runs-on: ubuntu-latest
    env:
      cxx_compiler: clang++-17

    steps:
      - uses: actions/checkout@v4

      - name: Only keep cpp changed files
        if: needs.get-changed-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ needs.get-changed-files.outputs.changed_cpp_files }}
        shell: pwsh
        run: ./.github/workflows/Remove-UnchangedFile.ps1

      - name: Install clang 17
        if: needs.get-changed-files.outputs.any_changed == 'true'
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod u+x llvm.sh
          echo | sudo ./llvm.sh 17

      - name: Check loser homework
        if: needs.get-changed-files.outputs.any_changed == 'true'
        uses: ./.github/actions/check-loser-homework
        with:
          build-path: ${{github.workspace}}/build
          extra-gen-params: "-DCMAKE_CXX_COMPILER=$cxx_compiler"

  check-in-msvc:
    needs: get-changed-files
    runs-on: windows-2022

    env:
      PYTHONIOENCODING: "utf-8"
      DOTNET_CLI_FORCE_UTF8_ENCODING: "true"

    steps:
      - uses: actions/checkout@v4

      - name: Only keep cpp changed files
        if: needs.get-changed-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ needs.get-changed-files.outputs.changed_cpp_files }}
        shell: pwsh
        run: ./.github/workflows/Remove-UnchangedFile.ps1

      - name: Check loser homework
        if: needs.get-changed-files.outputs.any_changed == 'true'
        uses: ./.github/actions/check-loser-homework
        with:
          build-path: ${{github.workspace}}/build
          shell: pwsh
          use-ninja: false